# Generated by Django 5.2.14 on 2026-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("support", "Staff"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
    ]
