# Generated by Django 5.2.14 on 2026-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution_note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
